global using AutoMapper;
global using Demo.BLL.DataTransferObjects.Departments;
global using Demo.BLL.DataTransferObjects.Employees;
global using Demo.BLL.Services.AttachmentService;
global using Demo.DAL.Models;
global using Demo.DAL.Models.Common;
global using Demo.DAL.Repositories;
global using Microsoft.AspNetCore.Http;
global using System.ComponentModel.DataAnnotations;
